project:
  type: book

book:
  title: "Python OR-tools Notes"
  author: "Kunlei Lian"
  date: "2/18/2023"
  google-analytics: "G-DTVHQH448R"
  chapters:
    - index.qmd
    - intro.qmd
    - env-setup.qmd
    - linear-programming.ipynb
    - integer-programming.ipynb
    - column-generation.ipynb
    - summary.qmd
    - references.qmd

website:
  google-analytics: "G-DTVHQH448R"

bibliography: references.bib

format:
  html:
    theme: cosmo
    include-in-header: mathjax.html
    html-math-method: mathjax
  pdf:
    documentclass: scrreprt



